// apps/web/src/app/recipes/page.tsx
import Link from "next/link";
import { AlertTriangle, ArrowRight, Clock, Tags, Utensils } from "lucide-react";
import { getRecipes } from "@/lib/api-client";

export const dynamic = "force-dynamic";

export default async function RecipesPage() {
  const { recipes, invalidRecipes } = await getRecipes();

  return (
    <div className="space-y-6">
      <section>
        <p className="text-sm font-medium uppercase tracking-wide text-moss">Recipes</p>
        <h1 className="mt-2 text-3xl font-semibold text-ink">CookLang recipe library</h1>
        <p className="mt-2 max-w-3xl text-ink/70">Valid local recipes available for planning.</p>
      </section>

      {invalidRecipes.length > 0 ? (
        <section className="rounded-md border border-tomato/30 bg-tomato/5 p-4">
          <div className="flex items-center gap-2 font-semibold text-tomato">
            <AlertTriangle size={18} aria-hidden="true" />
            Invalid recipe files
          </div>
          <div className="mt-3 space-y-3">
            {invalidRecipes.map((invalid) => (
              <div key={invalid.filePath} className="rounded-md bg-surface p-3 shadow-line">
                <p className="font-medium">{invalid.filePath}</p>
                <ul className="mt-2 list-disc pl-5 text-sm text-ink/70">
                  {invalid.errors.map((error) => (
                    <li key={error}>{error}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {recipes.map((recipe) => (
          <article key={recipe.id} className="rounded-md bg-surface p-5 shadow-line">
            <div className="flex min-h-full flex-col">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h2 className="text-lg font-semibold">{recipe.title}</h2>
                <p className="mt-2 text-sm leading-6 text-ink/65">{recipe.description}</p>
              </div>
              <span className="rounded-md bg-field px-2 py-1 text-xs font-medium text-ink/70">
                {recipe.defaultServings} servings
              </span>
            </div>
            <div className="mt-4 flex flex-wrap gap-2 text-sm text-ink/65">
              <span className="inline-flex items-center gap-1 rounded-md bg-field px-2 py-1">
                <Utensils size={14} aria-hidden="true" />
                {recipe.mealTypes.join(", ")}
              </span>
              <span className="inline-flex items-center gap-1 rounded-md bg-field px-2 py-1">
                <Clock size={14} aria-hidden="true" />
                {(recipe.prepTimeMinutes ?? 0) + (recipe.cookTimeMinutes ?? 0)} min
              </span>
            </div>
            {recipe.tags.length > 0 ? (
              <div className="mt-3 flex flex-wrap gap-2 text-xs text-ink/65">
                {recipe.tags.map((tag) => (
                  <span key={tag} className="inline-flex items-center gap-1 rounded-md bg-field px-2 py-1">
                    <Tags size={13} aria-hidden="true" />
                    {tag}
                  </span>
                ))}
              </div>
            ) : null}
            <div className="mt-5 flex items-center justify-between border-t border-ink/10 pt-4 text-sm text-ink/60">
              <span>
                {recipe.ingredientCount} ingredients · {recipe.cookwareCount} tools · {recipe.timerCount} timers
              </span>
              <Link
                href={`/recipes/${recipe.id}`}
                className="focus-ring inline-flex items-center gap-2 rounded-md px-2 py-1 font-semibold text-moss hover:bg-moss/10"
              >
                Details
                <ArrowRight size={15} aria-hidden="true" />
              </Link>
            </div>
            </div>
          </article>
        ))}
      </section>

      {recipes.length === 0 ? (
        <div className="rounded-md border border-dashed border-ink/20 bg-surface p-6 text-ink/70">
          No valid recipes found.
        </div>
      ) : null}
    </div>
  );
}

// apps/web/app/pages/recipes/index.vue
<script setup lang="ts">
import { callOnce } from "#app";
import { BookOpen, Search } from "@lucide/vue";
import { computed, ref } from "vue";
import { useRecipeModal } from "~/composables/use-recipe-modal";
import { useRecipesStore } from "~/stores/recipes";

const recipes = useRecipesStore();
const recipeModal = useRecipeModal();
await callOnce("recipe-catalog", () => recipes.fetchCatalog(), { mode: "navigation" });
const query = ref("");
const filteredRecipes = computed(() => {
  const normalized = query.value.trim().toLocaleLowerCase();
  const catalog = recipes.catalog?.recipes ?? [];
  if (!normalized) return catalog;
  return catalog.filter((recipe) => [recipe.title, recipe.description, ...recipe.tags]
    .filter(Boolean)
    .some((value) => String(value).toLocaleLowerCase().includes(normalized)));
});

function openRecipe(recipeId: string, trigger: globalThis.HTMLElement) {
  void recipeModal.openRecipe(recipeId, 2, trigger);
}
</script>

<template>
  <div class="mm-space-y-6">
    <section class="flex flex-col mm-gap-6 lg:flex-row lg:items-end lg:justify-between">
      <PageHeading eyebrow="Recipes" title="CookLang recipe library" description="Browse your trusted local collection and find the right meal in seconds." />
      <div class="flex w-fit shrink-0 items-center mm-gap-3 rounded-2xl border border-line/25 bg-surface px-4 py-3 shadow-sm">
        <span class="flex h-10 w-10 items-center justify-center rounded-xl bg-moss/12 text-moss">
          <BookOpen :size="20" aria-hidden="true" />
        </span>
        <div>
          <span class="block text-2xl font-bold leading-none tabular-nums">{{ recipes.catalog?.recipes.length ?? 0 }}</span>
          <span class="mt-1 block mm-text-xs font-semibold text-ink/65">recipes ready to cook</span>
        </div>
      </div>
    </section>
    <RecipesInvalidRecipeNotice
      v-if="recipes.catalog?.invalidRecipes.length"
      :invalid-recipes="recipes.catalog.invalidRecipes"
    />
    <section class="mm-panel mm-p-4 sm:p-5" aria-label="Recipe filters">
      <label class="relative block">
        <span class="sr-only">Search recipes</span>
        <Search class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-ink/50" :size="19" aria-hidden="true" />
        <input
          v-model="query"
          type="search"
          class="focus-ring mm-field w-full py-3 pl-11 pr-4 mm-text-base text-ink"
          placeholder="Search by recipe name, description, or tag…"
        />
      </label>
      <p class="mm-mt-3 mm-text-sm font-medium text-ink/65" aria-live="polite">
        Showing {{ filteredRecipes.length }} of {{ recipes.catalog?.recipes.length ?? 0 }} recipes
      </p>
    </section>
    <section class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
      <RecipesRecipeCard
        v-for="recipe in filteredRecipes"
        :key="recipe.id"
        :recipe="recipe"
        @open-details="openRecipe"
      />
    </section>
    <div
      v-if="filteredRecipes.length === 0"
      class="mm-panel border-dashed py-16 text-center text-ink/65"
    >
      {{ query ? "No recipes match your search." : "No valid recipes found." }}
    </div>
  </div>
</template>
