// apps/web/src/app/shopping/page.tsx
import { ShoppingListClient } from "@/components/shopping-list-client";
import { isPlanLocked } from "@mealmind/domain";
import { getCurrentShopping, getPlanningState } from "@/lib/api-client";

export const dynamic = "force-dynamic";

export default async function ShoppingPage() {
  const [{ activePlan, nextDraft }, currentShopping] = await Promise.all([
    getPlanningState(),
    getCurrentShopping(),
  ]);
  const plan = activePlan ?? nextDraft;
  const list = currentShopping.shoppingList;

  return (
    <div className="space-y-6">
      <section>
        <p className="text-sm font-medium uppercase tracking-wide text-moss">Shopping</p>
        <h1 className="mt-2 text-3xl font-semibold text-ink">Consolidated grocery list</h1>
        <p className="mt-2 max-w-3xl text-ink/70">Groceries for the selected meal plan.</p>
      </section>

      {plan ? (
        <ShoppingListClient
          planId={plan.id}
          items={list?.items ?? []}
          canRegenerate={!isPlanLocked(plan)}
        />
      ) : (
        <div className="rounded-md border border-dashed border-ink/20 bg-surface p-6 text-ink/70">
          No meal plan selected.
        </div>
      )}
    </div>
  );
}

// apps/web/app/pages/shopping.vue
<script setup lang="ts">
import { callOnce } from "#app";
import { computed } from "vue";
import { useShoppingStore } from "~/stores/shopping";
import { isPlanLocked } from "~/utils/plans";

const shopping = useShoppingStore();
await callOnce("shopping-current", () => shopping.fetchCurrent(), { mode: "navigation" });
const canRegenerate = computed(() => shopping.plan ? !isPlanLocked(shopping.plan) : false);
</script>

<template>
  <div class="mm-space-y-6">
    <PageHeading eyebrow="Shopping" title="Consolidated grocery list" description="Groceries for the selected meal plan." />
    <ShoppingList
      v-if="shopping.plan"
      :items="shopping.shoppingList?.items ?? []"
      :can-regenerate="canRegenerate"
    />
    <div v-else class="rounded-md border border-dashed border-ink/20 bg-surface mm-p-6 text-ink/70">
      No meal plan selected.
    </div>
  </div>
</template>
