// apps/web/src/components/commit-plan-button.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Lock, RefreshCw } from "lucide-react";

export function CommitPlanButton({ planId }: { planId: string }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function commit() {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(`/api/plans/${planId}/commit`, { method: "POST" });
      const payload = await response.json();
      if (!payload.ok) {
        throw new Error(payload.error?.message ?? "Could not commit plan.");
      }
      router.refresh();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-2">
      <button
        type="button"
        onClick={commit}
        disabled={busy}
        className="focus-ring inline-flex items-center gap-2 rounded-md bg-strong px-4 py-2 text-sm font-semibold text-strong-foreground hover:bg-strong/90"
      >
        {busy ? <RefreshCw size={16} className="animate-spin" aria-hidden="true" /> : <Lock size={16} aria-hidden="true" />}
        {busy ? "Committing" : "Commit plan"}
      </button>
      {error ? <p className="text-sm text-tomato">{error}</p> : null}
    </div>
  );
}

// apps/web/app/components/plan/CommitPlanButton.vue
<script setup lang="ts">
import { Lock, RefreshCw } from "@lucide/vue";
import { ref } from "vue";
import { errorMessage } from "~/composables/use-api";
import { usePlanningStore } from "~/stores/planning";

const props = defineProps<{ planId: string }>();
const planning = usePlanningStore();
const busy = ref(false);
const error = ref<string | null>(null);

async function commit() {
  busy.value = true;
  error.value = null;
  try {
    await planning.commit(props.planId);
  } catch (caught) {
    error.value = errorMessage(caught, "Could not commit plan.");
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div class="mm-space-y-2">
    <button
      type="button"
      :disabled="busy"
      class="focus-ring inline-flex items-center mm-gap-2 rounded-md bg-strong mm-px-4 mm-py-2 mm-text-sm font-semibold text-strong-foreground hover:bg-strong/90"
      @click="commit"
    >
      <RefreshCw v-if="busy" :size="16" class="animate-spin" aria-hidden="true" />
      <Lock v-else :size="16" aria-hidden="true" />
      {{ busy ? "Committing" : "Commit plan" }}
    </button>
    <p v-if="error" class="mm-text-sm text-tomato">{{ error }}</p>
  </div>
</template>
